#!/bin/bash
# One-time setup script for OrcaSlicer with Elegoo printer

echo "=========================================="
echo "OrcaSlicer Setup for Elegoo Centauri Carbon"
echo "=========================================="
echo ""
echo "REQUIRED: One-time GUI setup"
echo ""
echo "Step 1: Open OrcaSlicer"
echo "----------------------------------------"
echo "Opening OrcaSlicer now..."
open /Applications/OrcaSlicer.app
echo ""
echo "Step 2: Import your Elegoo printer config"
echo "----------------------------------------"
echo "In OrcaSlicer:"
echo "  1. Go to: File → Import → Import Configs..."
echo "  2. Navigate to: $(pwd)/config/printers/"
echo "  3. Select: Elegoo Centauri Carbon 0.4 nozzle.elegoo_printer"
echo "  4. Click 'Import'"
echo ""
echo "Step 3: Configure defaults"
echo "----------------------------------------"
echo "  1. Select printer: 'Elegoo Centauri Carbon 0.4 nozzle' (top-right dropdown)"
echo "  2. Select or create filament: PLA"
echo "  3. Select or create print preset: 0.20mm Standard"
echo "  4. Close OrcaSlicer (settings are saved automatically)"
echo ""
echo "Step 4: Test the slicer"
echo "----------------------------------------"
echo "Run: ./env/bin/python -m tests.test_slicer"
echo ""
echo "=========================================="
echo "Why is this needed?"
echo "=========================================="
echo "OrcaSlicer's CLI uses the settings configured in the GUI."
echo "The JSON/elegoo_printer files can't be used directly by the CLI."
echo "Once configured, the CLI will inherit those settings."
echo ""
