#!/bin/bash
# Helper script to configure OrcaSlicer for CLI usage

echo "==================================================================="
echo "OrcaSlicer Configuration Helper"
echo "==================================================================="
echo ""
echo "To use your Elegoo Centauri Carbon printer with the bot, follow these steps:"
echo ""
echo "1. Open OrcaSlicer application"
echo "   → macOS: open /Applications/OrcaSlicer.app"
echo ""
echo "2. Import your printer config:"
echo "   → Go to: File → Import → Import Configs..."
echo "   → Select: config/printers/Elegoo Centauri Carbon 0.4 nozzle.elegoo_printer"
echo ""
echo "3. Set as default printer:"
echo "   → In the printer dropdown (top right), select 'Elegoo Centauri Carbon 0.4 nozzle'"
echo "   → Configure filament: Select or create 'PLA' profile"
echo "   → Configure print settings: Select or create '0.20mm Standard' profile"
echo ""
echo "4. Save the configuration:"
echo "   → File → Export → Export Config Bundle..."
echo "   → Save to: config/printers/orca-complete-config.json"
echo ""
echo "5. Test slicing from CLI:"
echo "   → Run: python -m tests.test_slicer"
echo ""
echo "==================================================================="
echo "Alternative: The CLI will work with whatever printer/filament/print"
echo "settings are currently selected in your OrcaSlicer installation!"
echo "==================================================================="
